DROP TABLE IF EXISTS ENTRENAMIENTO ;
DROP TABLE IF EXISTS ACTIVIDAD ;
DROP TABLE IF EXISTS USUARIO ;

CREATE TABLE ACTIVIDAD  (
  codigo       INT NOT NULL IDENTITY PRIMARY KEY,
  tipo         VARCHAR(50) NOT NULL,
  duracion     INT NOT NULL,
  distancia    FLOAT NOT NULL
);

CREATE TABLE USUARIO  (
  codigo       INT NOT NULL IDENTITY PRIMARY KEY,
  nombre       VARCHAR(50) NOT NULL
);

CREATE TABLE ENTRENAMIENTO  (
  codigo            INT NOT NULL IDENTITY PRIMARY KEY,
  cod_usuario         INT NOT NULL,
  cod_actividad       INT NOT NULL,
  fecha             DATE NOT NULL, 
  FOREIGN KEY(cod_usuario) REFERENCES PUBLIC.USUARIO(codigo) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY(cod_actividad) REFERENCES PUBLIC.ACTIVIDAD(codigo) ON UPDATE CASCADE ON DELETE CASCADE 
);